### ISSUE TITLE
Bottom plate

### ISSUE THREAD

**Issue by jel111** [tobbelobb/hangprinter#11]
Having problems printing bottom plate. It staggers all the layers. i have printed everything else just fine. I am hoping you could take a look at that file for me. thanks John!

**Comment by tobbelobb** [comment]
Take a look at your gcode (use http://gcode.ws/ or Slic3r or any tool you like). If you can't see staggering there, then the printer is the problem.

Example in Slic3r: 
![selection_001](https://cloud.githubusercontent.com/assets/5753253/25065455/b84146a4-2210-11e7-9792-bdb9f08f9a70.png)
