### ISSUE TITLE
Gear System Issue

### ISSUE THREAD

**Issue by PavloNikitiuk07** [tobbelobb/hangprinter#13]
Hey! There's also another issue I've ran into.

Should there be any additional holes in the sides of the gear for lace to go through? Cause I've made an additional hole in the side of the gear for that. Did I do it wrong?

Here are some photos of what I mean:
https://goo.gl/photos/LjXdNViA3kfSeRv28
https://goo.gl/photos/9uA4jrHUeYwvaGfo6

**Comment by tobbelobb** [comment]
I connect all strings through the two holes included in the 3d model.

Your lines look a fair bit thicker than the ones I usually use though. See the facebook group for suggestions and discussions on specific types of lines: https://www.facebook.com/groups/hangprinter (one example here: https://www.facebook.com/groups/hangprinter/permalink/187803785063122/?match=bGluZXMsbGluZQ%3D%3D )
