### ISSUE TITLE
Gear Movement issue

### ISSUE THREAD

**Issue by PavloNikitiuk07** [tobbelobb/hangprinter#14]
Another issue I've encountered is that Gear D (the most bottom one) move a little up and down, which makes it wobble on the sides. Currently I've hooked a washer to the gear above it to fix temopraly.

Is there a better solution to this problem?

**Comment by tobbelobb** [comment]
I use grease on my worm, but still, mine wobbles a little as well. Hasn't been a problem though.

**Comment by tobbelobb** [comment]
If I understand the issue right, then a piar of large diameter thrust bearings (above and below D-sandwich) would probably help?
