### ISSUE TITLE
Issues Getting Files

### ISSUE THREAD

**Issue by JTonerII** [tobbelobb/hangprinter#17]
Hello,
I really like this project and would like to build it. However, I'm new to scad and when I try to copy/paste the lines of code into Open SCAD-->Preview or Render. I keep getting a Syntax Error. How do I successfully get these files to turn them into .stl files? Thank you,
JTonerII

**Comment by tobbelobb** [comment]
There's no need to use OpenSCAD if you only want the standard Hangprinter parts.

The version 2 is on the master branch. It has stls in a directory called [stl](https://github.com/tobbelobb/hangprinter/tree/master/stl). Version 3 (which I recommend) is on the Openscad_version_3 branch. It has stls in a directory called [openscad_stl](https://github.com/tobbelobb/hangprinter/tree/Openscad_version_3/openscad_stl).

Copy/pasting code from the browser is not how Github is meant to be used. I cannot teach you git and Github here, but this is how you download the stls:
 * Go to the file you want to download.
 * Click it to view the contents within the GitHub UI.
 * In the top right, right click the Raw/Download button.
 * Save as.../Save link as...

**Comment by tobbelobb** [comment]
The version 2 files all have a `qty_X.stl` ending to denote how many to print. The version 3 qtys are specified in the [bill of materials](https://github.com/tobbelobb/hangprinter/tree/Openscad_version_3#bill-of-materials).
