### ISSUE TITLE
Uploads Are Disabled

### ISSUE THREAD

**Issue by JTonerII** [tobbelobb/hangprinter#18]
Not able to upload .stl files. Get a message that sat "Uploads are Disabled" "File Uploads Require Push Access to this Repository" Can the files be made to be uploadable, please? Thank you,   James

**Comment by tobbelobb** [comment]
What files do you want to upload?

**Comment by johnnyjeannatasha** [comment]
Unblock uploads

**Comment by tobbelobb** [comment]
Sorry, this is a git repo, there's no such thing as unlock or upload.

You will need to clone the repo and make a push request. The Github repo is just a mirror, so I prefer pull requests (aka merge requests) to be submitted to the repo at Gitlab, here: https://gitlab.com/tobben/hangprinter
