### ISSUE TITLE
Openscad Bug with new 55mm spool design

### ISSUE THREAD

**Issue by msross** [tobbelobb/hangprinter#19]
When attempting to render spool.scad, Openscad processes for several minutes.  When it completes, the viewport shows several objects that should not be in the spool design and those object must be CPU intensive, because it is difficult to re-orient the view to see what is going on.

I have isolated the bug to the following calls:
18    for(i=[0:60:359])
19      rotate([0,0,i])
20       spool_decoration();

I will try to research more later today.

**Comment by tobbelobb** [comment]
It's true that the spool decoration is coded in a CPU intensive way, and that OpenSCAD gives up after a ceirtain amount of facets. A new, more efficient decoration would be greatly appreciated!

**Comment by tobbelobb** [comment]
The super-inefficient coding comes down to me wanting rounded corners... A possible solution is to compile the stls with ImplicitCAD and get rounded corners for much cheaper. Would you support such a change or is ImplicitCAD too exotic?

**Comment by msross** [comment]
I will take a look and see if we can get the effect in a more efficient way.  I am not opposed to ImplicitCAD.  If someone is willing to go to OpenScad, they are probably willing to try ImplicitCAD.

**Comment by tobbelobb** [comment]
I worked on stabilizing the spool core today, and needed to also rationalize the spool in the process to get visual double check in renderings. It might be optimized enough that you can do what you originally intended to do with the spool.scad code. Best regards

https://github.com/tobbelobb/hangprinter/commit/d67e9901c6ce03590cf3b91fe5b0acd4953dc34a
