### ISSUE TITLE
SCAD file missing

### ISSUE THREAD

**Issue by knkrth** [tobbelobb/hangprinter#2]
Hi some of the scad files are missing you did update #include .scad file but you didn't upload those files . can you upload those files?

**Comment by tobbelobb** [comment]
Hi!
I'm unable to replicate your error. Which files and which branch?

Line 32 and 37 in Hangprinter.scad on the master-branch tries to import precompiled stl-files which aren't in the repo, that's all I can find. Removed them and pushed a commit so you don't have to search for them.

**Comment by knkrth** [comment]
thanks
