### ISSUE TITLE
Moving anchors - horizontal axes

### ISSUE THREAD

**Issue by DegenerateGroundState** [tobbelobb/hangprinter#20]
The hangprinter uses stationary anchors for the horizontal axes' lines and this means the build volume is constrained because of potential overlap, right? If instead the anchors move up (on rails perhaps) as the build platform moves up, the build volume would not decrease with height, correct?

I realize this would add significant cost and complexity, but it could be optional, depending on how much work this would take in software of course.

**Comment by tobbelobb** [comment]
Yes, you are correct. When I printed the Babel Tower, I moved the ABC anchors on every printed meter and re-calibrated anchor positions. See my blog posts from Feb-March 2017 for details about that.
