### ISSUE TITLE
Missing lineroller_parameters.scad for 'make layout'

### ISSUE THREAD

**Issue by jdegenstein** [tobbelobb/hangprinter#24]
I noticed a (very minor) issue with creating the layout_letter.pdf. The lineroller_parameters.scad file appears to have been merged into parameters.scad. As a result of this, the command 'make layout_letter.pdf' fails.

Commenting out/deleting the appropriate lines in the Makefile appears to solve this issue, and the layout_letter.pdf is generated successfully. I believe the same issue applies to the other layout types, but I did not test it.

Just thought I would throw this out in case anyone has this issue.

**Comment by tobbelobb** [comment]
Thanks for catching this and sorry for the late reply, I've been away on holidays.

I had also forgotten to remove references to 'gear_parameters.scad'. I pushed a fix on Gitlab: https://gitlab.com/tobben/hangprinter/commit/7600ec37a66ab559740eb81918174f655c3ed832

PS! Future development will be on Gitlab, I'll make a note in the Github Readme now ;)
