### ISSUE TITLE
Closed Loop stepper motor

### ISSUE THREAD

**Issue by Tesla3DTore** [tobbelobb/hangprinter#4]
Hi,

Amazing JOB that your are doing until now!!! I would like to help you to improve your NEXT STEP of 3d printer that i'm sure will be the award of 2017!!!

You need a more precise stepper motor 16 or 32 step is not enought!!!
You need 256 step with a closed loop system so look at that project:

Wembi:
https://www.kickstarter.com/projects/109167261/wembi-closed-loop-motorupgrade-for-3d-printer?lang=fr

or

Mechaduino (open source):
https://github.com/jcchurch13

but for me a 32 bit controller with 256 microstepping is a must that you need to test so go here:
http://smoothieware.org/smoothieboard and look the V2 model (round shape ;-) )

I will print now your printer and add this features and give you feedback as soon as possible...

Best Regards,
Greg

**Comment by tobbelobb** [comment]
Thanks!

Looking forwards to your contributions.
