### ISSUE TITLE
Which file should I print?

### ISSUE THREAD

**Issue by Eric-Furman** [tobbelobb/hangprinter#7]
should I print bottom_plate or Bottom_Plate2?

**Comment by tobbelobb** [comment]
Oh, thanks for notifying. There's only supposed to be one bottom plate in the stl directory.

Bottom_plate_qty_1.stl is the "known to work" one. Bottom_plate2_qty_1.stl has slightly simplified (but untested) D-action points and no engraved letters.

I removed the old Bottom_plate_qty_1.stl. Only the untested one is left in the stl folder. It has changed name to Bottom_plate_qty_1.stl.

**Comment by tobbelobb** [comment]
The answer to your question is: any of them is fine. :+1:

**Comment by Eric-Furman** [comment]
Thank you
