### ISSUE TITLE
replacement part

### ISSUE THREAD

**Issue by Eric-Furman** [tobbelobb/hangprinter#8]
hello, I was watching the interview with you and Thomas Sanladerer and you stated that you could replace the 2.7mm Eyes Inside Dia Fishing Rod Part with Bowden tubes.  I wanted to know how that could be done because I cannot seem to find the fishing rod part near me.  
Thank you

**Comment by tobbelobb** [comment]
Designing a PTFE eye wouldn't be hard, but then the ease of searching ebay has made me lazy (save some time). Search for example "2.8mm Dia Connector Ring" or "2.8mm Dia Fishing Rod Guide Repair Kit 5pcs" or similar...

If you can't wait for shipping, a pull request is most welcome!
