### ISSUE TITLE
individual components in scad? 

### ISSUE THREAD

**Issue by robssm** [tobbelobb/hangprinter#9]
Tobben,

I think perhaps the eyelet pillars on the botttom plate may benefit from some added ribs to increase the rigidity in some areas, maybe even the motor mounts also? 

Can we get the scad for the bottom plate so it may be edited and reinforced? 

I realize its all overkill, however, with the manner in which I am going to implement the hangprinter, this may become an issue ie in a heated enclosure.

**Comment by tobbelobb** [comment]
Enforcing ribs is a good idea! The areas around the hole for the worm could also need some reinforcement.

An alternative way to reinforce is to control the level of infill. Modifiers in Slic3r is a good tool for that. 

bottom_plate begins on line 158 in parts.scad
https://github.com/tobbelobb/hangprinter/blob/master/parts.scad#L158
